### ISSUE TITLE
I18n - possibilidade de trazer meses em português

### ISSUE THREAD

**Issue by PetersonFonsec** [nncl/ngx-datepicker#21]
Seria interessante ter a possibilidade de visualizar o mês em português exemplo: ao invés de mostrar September mostrar Setembro.

**Comment by nncl** [comment]
@PetersonFonsec como o módulo trabalha com o **moment** é possível setar a internacionalização através dele globalmente no seu app:

**app.module.ts**
```typescript
// ... imports
import * as moment from 'moment';

moment.locale('pt-BR');
```

![Screen Shot 2020-10-19 at 1 45 16 PM](https://user-images.githubusercontent.com/6740387/96481004-54b7ae80-1211-11eb-9117-83368db198ff.png)

**Comment by nncl** [comment]
Vou adicionar na documentação essas informações na próxima versão.

@PetersonFonsec obrigado pela sugestão 👍

**Comment by nncl** [comment]
Eu vou reabrir a issue pois ainda não atualizamos a documentação.

**Comment by nncl** [comment]
Documentação atualizada conforme versão 1.6.0:

https://github.com/nncl/ngx-datepicker#i18n
https://www.npmjs.com/package/@clmeida/ngxdatepicker#i18n

@PetersonFonsec sugiro atualizar o módulo em sua aplicação:

```
"@clmeida/ngxdatepicker": "^1.6.0",
```
