### ISSUE TITLE
Possibilidade de adicionar sufixos no mês

### ISSUE THREAD

**Issue by PetersonFonsec** [nncl/ngx-datepicker#24]
Seria interessante ter a possibilidade de adicionar um sufixo apos o mês selecionado, ao invez de mostrar apenas setembro poderia mostrar `setembro ${sufix}`. Sim lib teria uma versatilidade maior, dessa forma seria possível mostrar o mês de N formas diferentes exemplo: Setembro de 2020. 

Mas claro é apenas uma sugestão.

**Comment by nncl** [comment]
@PetersonFonsec na versão 1.7.0 é possível trabalhar com o slot `month` conforme a doc.
