### ISSUE TITLE
Existe alguma forma de dizer que um determinado dia deve ser desabilitado ?

### ISSUE THREAD

**Issue by PetersonFonsec** [nncl/ngx-datepicker#25]
Exemplo eu tenho um calendário com dias disponíveis para fazer um reserva. existe alguma forma de dizer que determinado dia não esta disponível e que dever ser desabilitado ? ou que dias menores que o dia atual devem ser desabilitados ?

**Comment by nncl** [comment]
@PetersonFonsec atualmente não existe, mas acho que é uma funcionalidade legal de se existir, visto que também já tive essa necessidade em alguns projetos.

Quando você fala:
  > "ou que dias menores que o dia atual devem ser desabilitados"

Você quer dizer o dia atual **selecionado** ou o dia de hoje?

A sua necessidade é desabilitar todos os dias anteriores a hoje ou datas específicas?

**Comment by PetersonFonsec** [comment]
@nncl apenas datas específicas.

**Comment by nncl** [comment]
@PetersonFonsec entendo, eu posso implementar uma propriedade que recebe um array de timestamps e verificamos se a data do calendário é igual a algum dos dias desse array, ex:

```html
<dd-ngxdatepicker
  name="date"
  [(ngModel)]="date"
  [invalidDates]="invalidDates"
></dd-ngxdatepicker>
```

```typescript
class MyComponent implements OnInt {
  invalidDates = ["2020-10-09T00:00:00-03:00", "2020-10-10T00:00:00-03:00"]
}
```

O que acha? Você tem alguma sugestão?

De qualquer forma também acho válido adicionar uma propriedade que informa se devemos ou não desabilitar datas anteriores ao dia de hoje, acho que é uma necessidade em alguns projetos também.

**Comment by PetersonFonsec** [comment]
@nncl interessante gostei, eu tenho uma sugestão. Seria possível o componente receber uma função como parâmetro ? e essa função ser disparada para cada dia do calendário ? 

exemplo : `<dd-ngxdatepicker [dateIsValid]="(day) => {{ alguma condição }} ? true : false"></dd-ngxdatepicker>` 

ai desabilita o dia de acordo com o resultado da função enviada. Assim acho que da mais liberdade para o desenvolvedor criar a regra que quiser.

**Comment by nncl** [comment]
@PetersonFonsec mas você não acha que o array que você passará através de uma propriedade do componente poderá ser montado de acordo com a vontade do desenvolvedor?

Além disso, no seu exemplo, como ficaria se você precisasse invalidar mais de uma data?

**Comment by nncl** [comment]
Publiquei os ajustes na branch **1.8.0-alfa**, realizarei alguns testes a mais e até amanhã publico a nova versão em produção junto à documentação.

RC de doc:

```typescript
export class AppComponent implements OnInit {
  invalidDates: string[] = [];

  ngOnInit() {
    const tomorrow = moment().add(1, 'days').format();
    const someDayOfNextMonth = moment().add(1, 'month').format();
    this.invalidDates.push(tomorrow);
    this.invalidDates.push(someDayOfNextMonth);
  }
}
```

```html
<dd-ngxdatepicker
  [invalidDates]="invalidDates"
  [disablePrevDates]="true">
</dd-ngxdatepicker>
```

**Comment by PetersonFonsec** [comment]
> @PetersonFonsec mas você não acha que o array que você passará através de uma propriedade do componente poderá ser montado de acordo com a vontade do desenvolvedor?

@nncl verdade eu não tinha pensado dessa forma acho que deixa até mais simples. boa idea 👍

**Comment by nncl** [comment]
Nova versão - 1.8.0 - publicada:

https://www.npmjs.com/package/@clmeida/ngxdatepicker#properties

@PetersonFonsec qualquer sugestão é bem vinda.
